### ISSUE TITLE
not sure if its an issue or not or im doing something wrong.

### ISSUE THREAD

**Issue by Whal93** [Broooklyn/runelite-external-plugins#45]
basically i want to mute everyone elses annoying sounds. levelling up, pet stomping etc. 

but i want to keep all those sounds that i make, when i mute them, it mutes my sounds and other peoples. is there a way to just mute others and not mine?

if not, maybe an update to add this?

**Comment by Broooklyn** [comment]
Generally, this isn't something that is possible due to how sounds are received by the client. For example, there is no way to distinguish between the stomp of your Skotos pet versus the Skotos pet of the guy next to you--it's all the same clientside. Currently, I have this in place for others' teleport sounds, but it's more of a forced/hacky solution and doesn't even work perfectly (e.g., if you teleport at the same time as someone else, you'll hear their teleport). It comes down to there being way too many things to hack together, most of which probably wouldn't work properly, so it's not a direction I wish to take, sorry.

**Comment by Whal93** [comment]
not a problem, thank you for the reply. its an excellent plugin all the same

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
