### ISSUE TITLE
Add Area Mutes 

### ISSUE THREAD

**Issue by TeamPositiveYT** [Broooklyn/runelite-external-plugins#82]
Add area mutes to mute magic trees and furnaces. It's written in RL "Music" plugin, so you may be able to just reference the client.java file where the call to the function in MusicConfig.java is referenced and initialized? Would be super dope! I see quite a few threads on Reddit, wishing this was a feature of your plugin. Much love <3

**Comment by TeamPositiveYT** [comment]
https://github.com/runelite/runelite/blob/b6fc61a7abaccc58760def25f75305dd4f1f1e6e/runelite-api/src/main/java/net/runelite/api/Client.java#L2017

https://github.com/runelite/runelite/blob/d7dd8d653805f59bc07d45c025a564a547dc1432/runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java#L236

**Comment by JZomDev** [comment]
I added Magic Trees in https://github.com/Broooklyn/runelite-external-plugins/commit/bda54623af1a75e0fbf8b1e9577708e1ce7f7524 

It's sorta hard to add them by hand because as a end user you can't get this list without launching dev mode and looking at the ambient sounds loaded to the local client but if you want more muted sounds feel free to make a suggestion for them!
